---
  title: "Data Management Training Exercises"
author: "Brian K"
date: "2023-07-25"
output:
  rmarkdown::html_document:
  theme: cosmo
toc: no
toc_float: no
code_folding: hide
code_downlod: yes
highlight: textmate
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Data Management Exercise {.tabset}

## Welcome 

For this training will be looking at R using the [Rstudio IDE](https://posit.co/download/rstudio-desktop/). IDE `Integrated Development Environment` software interface that makes it easier to work with programming languages in other softwares we have the likes of `Visual Studio, Pycharm, Spider e.t.c`.


### Assumptions

Have some limited or little knowledge of Microsoft excel functions e.g `=sum(C1,C2)`, though not mandatory it makes it easier to grasp concepts slightly faster.
Though if you remember the simple mathematics we do everyday of summing and adding money then you are good :).

### Requirements

* Working computer (Laptop/Desktop)
* Access to internet once in a while to download a few resource materials
* **Interest and desire** to learn new concepts


### Overview of our knowledge

* Installation of R
* Installation of RStudio
* Interface familiarization
* Shortcuts for life Using Rstudio



### Teaching guide

* Mixed instructional guide, with the presentation but focused on getting more hard skills
* Prepare to write R codes
* Engagements and practice on the fly



## Day 1 {.tabset .tabset-pills}



### Navigating RStudio

**Key Guiding Concepts**
  
  - **Four panels**
  
  Rstudio Panels: 
  
  ![https://docs.posit.co/ide/user/ide/get-started/images/rstudio-panes-labeled.jpeg](Images/rstudio-panes-labeled.jpeg)

- **Source Panel:** 
  
  Write you R code in scripts use it as a text editor


- **Console Panel:** 
  
  Terminal window with link to R software, printing commands that are executed


- **Environments Panel:** 
  
  Show content in the R Environment:
  * R Objects
* Functions
* Loaded package work spaces


- **Output Panel:**
  
  1. Contains outputs generated by the code graphs and webpage instances.
2. Packages installed 
3. File and folder selection


- **Package Handling**
  
  - Installed Base R packages
- Installing Packages
- Removing install packages
- Loading packages




### R Markdown


Because seeing is believing we will start, with your first shot of creating your first default **RMarkdown** document. To impress and get us going.



* What is RMarkdown?
  - Hyptertext document, using word formatting to create documents, websites and even dashboards
- In simple words righting short forms that are translated to features within the document



* Why RMarkdown?
  - Easiest entry to so many features of sharing information, reports and training
- Very easy to pick up how to learn





This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:
  
  ```{r cars}
summary(cars)
```

#### Including Plots

You can also embed plots, for example:
  
  ```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

**Rmarkdown | Cheat Sheets**
  
  [Rmarkdown](https://rstudio.github.io/cheatsheets/html/rmarkdown.html)


## Day 2 {.tabset .tabset-pills}

### Tidyverse

Tidyverse stems out of [Hardley Wickham](https://www.rstudio.com/authors/hadley-wickham/) work on developing tidy datasets. Data in tabular format with columns having the variable/Fields while rows have observations/case.

Tidy Data format: ![Image courtesy, https://d33wubrfki0l68.cloudfront.net/6f1ddb544fc5c69a2478e444ab8112fb0eea23f8/91adc/images/tidy-1.png](Images/tidydata.png) 

R is built of inbuilt functions, and because of use by different individuals. In the spirit of reducing workload they develop compilation of functions that they use frequently called **Packages**. This packages are available online for approved ones under respisitory [CRAN](https://cran.r-project.org/)



Tidyverse Packages has collection of the below packages:
  
  
  
  Package | Description
--------|------------
  dplyr   | Data manipulation package
tidyr   | Tidyfying data package
stringr | Working on string functions
ggplot2 | Visualization through graphs
readr   | Importing data formats to R environment
tibble  | Improved data frame
forcats | Dealing with categorical factor data formats
purrr   | Main purpose for functional programming i.e. advanced loops


We might not get the chance to look at all of them but we will focus on 3 and an extra 1. Though we will go thorugh some of them as we proceed through the session.





## Day 3 {.tabset .tabset-pills}

### Introduction to dplyr & tidyr

1. Importing data from excel using read_excel.
2. Using function `pivot_wider` to transpose longer data to wider data
3. Using function `pivot_longer` to transpose wide data to long data format
4. `lubridate` date package recap of the functions used `month` and `quarter`
5. Aggregation of data similar to pivot tables in excel using `summarise` function and calculating `mean, sum`


### Other learnings on excel

Formulas learnt

* `=search()`
* `=mid()`
* `=iferror()`
* `=left()`
* `=right()`

Using real life data to test.


## Day 4 {.tabset .tabset-pills}

### Regression 

For regression we will learn on how to use `lm` function to achieve `linear regression` of datasets.

**Using our height weight data**
  
  1. Testing correlation

Sample code 

`cor`

2. Testing linear regression

Sample code 
`sim1_mod <- lm(y ~ x, data = sim1)
coef(sim1_mod)`


## Day 5 {.tabset .tabset-pills}