---
title: "Data Management Training Exercises"
author: "Brian K"
date: "2023-07-25"
output:
  rmarkdown::html_document:
  theme: cosmo
toc: no
toc_float: no
code_folding: hide
code_downlod: yes
highlight: textmate
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Data Management Exercise {.tabset}

## Welcome 

This week we are doing exercise, and focus of exercise will be on the three software done during the training.

1. MS Excel
2. R
3. PowerBi


### 1. MS Excel

General use and understanding of Microsoft excel. Maneouvering through workbooks, sheets and formulas.

Intertwined understanding of how formulas work with sheets across workbooks.

### 2. R Software

Statistical software used for analysis.

Work around understanding of what R Software is and familirazation to the IDE RStudio


### 3. PowerBI

Software tool used for visualization and story telling.

Creation of dashboards that are feed directly from raw data format.

Introduction of the interface, use of visuals and how to change functions.

Understanding of how to manipulate data on the data structure end.


### Overview of our knowledge

* Installation of MS Excel
* Installation of R
* Installation of RStudio
* Installation of PowerBI
* Interface familiarization



### Teaching guide

* Mixed instructional guide, with the presentation but focused on getting more hard skills
* Engagements and practice on the fly



## Day 1 {.tabset .tabset-pills}




## Day 2 {.tabset .tabset-pills}


## Day 3 {.tabset .tabset-pills}



## Day 4 {.tabset .tabset-pills}



## Day 5 {.tabset .tabset-pills}